version: '3.7'
 
services:
  app: 
    build: .
    image: clean-node-api
    container_name: suvey-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - 5050:5050
      - 9222:9222
    depends_on:
      - mongo
    networks: 
      - survey-network
 
 
  mongo:
    image: mongo
    container_name: database-survey
    restart: always
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    networks: 
      - survey-network
 
networks: 
    survey-network:
      driver: bridge
 
volumes: 
  data:
    driver: local