version: '3.7'
 
services:
  app: 
    image: node:16
    working_dir: /usr/src/clean-node-api
    container_name: suvey-api
    restart: always
    command: bash -c "npm install --omit=dev && npm install nodemon -D && npm run debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    ports:
      - 5050:5050
      - 9222:9222
    depends_on:
      - mongo
    networks: 
      - survey-network
 
 
  mongo:
    image: mongo
    container_name: database-survey
    restart: always
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    networks: 
      - survey-network
 
networks: 
    survey-network:
      driver: bridge
 
volumes: 
  data:
    driver: local